name: dart_example
homepage: https://dev-cetera.com/
repository: https://github.com/robmllze/df_di
funding:
  - https://www.buymeacoffee.com/dev_cetera
description: A sample command-line application.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  df_di:
    path: ../../

dev_dependencies:
  lints: ^6.0.0
  test: ^1.26.2

