name: dart_example
description: A sample command-line application.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.7.0

dependencies:
  df_di:
    path: ../

dev_dependencies:
  lints: ^6.0.0
  test: ^1.24.0
