name: di_vs_get_it_speed_test
homepage: https://dev-cetera.com/
repository: https://github.com/robmllze/df_di
funding:
  - https://www.buymeacoffee.com/dev_cetera
environment:
  sdk: ">=3.5.0 <4.0.0"
dependencies:
  df_di:
    path: ../../
  get_it:
dev_dependencies:
  lints: ^6.0.0


